### REGISTRATION
POST localhost:8080/api/v1/auth/registration
Content-Type: application/json
Accept-Language: UZ


{
  "name": "sezr",
  "username": "998884973535",
  "password": "22281"
}

###Registration verification
GET http://localhost:8080/auth/registration/verification/{profileId}


### Sms Registration verification
POST localhost:8080/api/v1/auth/registration/sms/verification
Content-Type: application/json

{
  "phone": "998884973535",
  "code": "97834"
}



### Login
POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "ulugdev71@gmail.com",
  "password": "12345"
}